---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: gd-kong-gateway
          env:
            - name: KONG_DATABASE
              value: "off"
            - name: KONG_PROXY_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_ADMIN_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_PROXY_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_ADMIN_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_LOG_LEVEL
              value: "warn"
            - name: KONG_DECLARATIVE_CONFIG
              value: "/usr/local/kong/declarative/kong.yml"
            - name: KONG_ADMIN_LISTEN
              value: "0.0.0.0:8001,0.0.0.0:8444 ssl"
            - name: KONG_PROXY_LISTEN
              value: "0.0.0.0:8000,0.0.0.0:8443 ssl,0.0.0.0:9080 http2,0.0.0.0:9081 http2 ssl"
          ports:
            - containerPort: 8001
            - containerPort: 8444
            - containerPort: 8000
            - containerPort: 8443
            - containerPort: 9080
            - containerPort: 9081

---
apiVersion: v1
kind: Service
metadata:
  name: kong
spec:
  selector:
    app: kong
  ports:
    - name: admin
      protocol: TCP
      port: 8001
      targetPort: 8001
    - name: admin-ssl
      protocol: TCP
      port: 8444
      targetPort: 8444
    - name: proxy
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: proxy-ssl
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: proxy-http2
      protocol: TCP
      port: 9080
      targetPort: 9080
    - name: proxy-http2-ssl
      protocol: TCP
      port: 9081
      targetPort: 9081
