

apiVersion: v1
kind: Namespace
metadata:
  name: gd-users

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-ms
  namespace: gd-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-ms
  template:
    metadata:
      labels:
        app: user-ms
    spec:
      containers:
        - name: user-ms
          image: gd-users-ms
          ports:
            - containerPort: 3005
          env:
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_USER
              value: "postgres"
            - name: DB_HOST
              value: "user-db"
            - name: DB_NAME
              value: "users_ms"
          volumeMounts:
            - name: migration-volume
              mountPath: /app/db/migrations
            - name: script-volume
              mountPath: /app/scripts
      volumes:
        - name: migration-volume
          configMap:
            name: user-ms-migrations
        - name: script-volume
          configMap:
            name: user-ms-scripts

---
apiVersion: v1
kind: Service
metadata:
  name: user-ms
  namespace: gd-users
spec:
  selector:
    app: user-ms
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  namespace: gd-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
        - name: user-db
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_DB
              value: "users_ms"

---
apiVersion: v1
kind: Service
metadata:
  name: user-db
  namespace: gd-users
spec:
  selector:
    app: user-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
